#!/usr/bin/env bash
#displays 1 to 100 with fizz in multiples of 3, "Buzz" in multiples
#of 5 and "FizzBuzz" in multiples of both 3 and 5.

for n in {1..100}
do
	if (( n % 3 == 0 && n % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( n % 3 == 0 ))
	then
		echo "Fizz"
	elif (( n % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$n"
	fi
done
