#!/usr/bin/env bash
#Loops from 1 to 10 with "bad luck" in 4th, "good luck" in 8 and "Best School"

c=0

while [ $c -lt 10 ]
do
	if [ $c -eq 3 ]
	then
		echo "bad luck"
	elif [ $c -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( c++ ))
done
